[project]
name = "claude-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=1.2.0",
    "ollama>=0.6.2",
    "pyyaml>=6.0.3",
]

[project.scripts]
claude-py = "claude_py.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/claude_py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"